fix: usage of `a deprecated Node.js version`
vercel/ncc pull request #1231
Opened 2024-11-17 23:48 UTC by hamirmahal

Fixes #1230

2024-11-17 23:49 UTC, hamirmahal commented on .github/workflows/ci.yml
> +        uses: actions/setup-python@v5
`v5` is the latest major version of this action at the time of this writing.

2024-11-18 16:05 UTC, styfle requested changes
Thanks for the PR!

Please revert all the whitespace changes so its clear what is changing. Changes to formatting can happen in a different PR than code changes.

2024-11-18 20:49 UTC, hamirmahal commented
You're welcome!

I reverted the changes from formatting on save.

2024-11-18 21:04 UTC, styfle commented on .github/workflows/ci.yml
> +      uses: actions/setup-python@v5
```suggestion
      uses: actions/setup-python@v5
      -- force ci
```

2024-11-18 21:05 UTC, styfle commented on .github/workflows/ci.yml
> +      -- force ci
```suggestion
```

2024-11-18 21:05 UTC, styfle approved these changes

2024-11-18 21:22 UTC, merged